name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (CI test)
        working-directory: backend
        run: |
          docker build -t backend-test .

      - name: CI success
        run: echo "Build completed successfully"

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulated deploy step
        run: |
          echo "CD pipeline triggered"
          echo "Deployment"
